apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb-sensors
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: sensors
    user: telegraf
    secureJsonData:
      password: telegraf
    jsonData:
      httpMode: GET
    isDefault: true
