[agent]
  interval = "5s"
  flush_interval = "10s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["sensors/#"]
  data_format = "value"
  data_type = "float"
  name_override = "sensor_data"

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "sensors"
  username = "telegraf"
  password = "telegraf"
  skip_database_creation = true
